services:
  - type: web
    name: superset
    env: python
    plan: free
    buildCommand: |
      chmod +x render-build.sh
      ./render-build.sh
    startCommand: |
      gunicorn -w 4 -k gthread --timeout 300 --bind 0.0.0.0:10000 "superset.app:create_app()"
    envVars:
      - key: SUPERSET_SECRET_KEY
        value: "your_random_secret_key_here"
      - key: SUPERSET_DATABASE_URI
        fromDatabase:
          name: superset-db
          property: connectionString

databases:
  - name: superset-db
    plan: free
