services:
  - type: web
    name: superset
    env: python
    buildCommand: ./render-build.sh
    startCommand: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin
          --username admin
          --firstname Superset
          --lastname Admin
          --email admin@admin.com
          --password admin || true &&
        superset init &&
        gunicorn -w 4 -k gthread --timeout 60 --bind 0.0.0.0:8080 'superset.app:create_app()'
      "
