services:
  - type: web
    name: superset
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn -w 4 -k gthread --timeout 60 --bind 0.0.0.0:8080 "superset.app:create_app()"
    envVars:
      - key: SUPERSET_ENV
        value: production
      - key: FLASK_APP
        value: superset
